apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-optima.fullname" . }}-control-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent-optima.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-api
spec:
  type: {{ .Values.controlApi.service.type }}
  ports:
    - port: {{ .Values.controlApi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "agent-optima.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: control-api
